# CollectionBuilder 
# Jekyll Digital Collection Generator

# URL variables
# site domain 
url: https://www.clarivatevivo.com
# location on the domain
# e.g. /digital/hjccc
baseurl: /collection
# CONTENTdm server url
cdm-url: https://digital.lib.uidaho.edu
# location of code
source-code: https://github.com/CollectionBuilder

# Site settings
title: My Very Interesting Collection
# header and head metadata
tagline: Digital Collection Magic with Statistically Revevant Web Technologies
description: "I am doing something productive, and this site is honest proof of that."
# Organization branding
organization-name: "Web of Science Group"
organization-link: https://www.lib.uidaho.edu/digital/
organization-logo-banner: https://clarivatevivo.com/themes/wos-bootstrapped/images/Clarivate-vivo-logo.png
organization-logo-nav: https://clarivatevivo.com/themes/wos-bootstrapped/images/Clarivate-vivo-logo.png

# Collection settings
# contentdm collection name 
cdm-collection-id: psychiana
# name of metadata file, be sure to also change page_gen data setting!
metadata: demo_psychiana 
# page gen settings 
# "data" value must be the name of the metadata file
page_gen:
  - data: 'demo_psychiana'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html'   

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# if present, used to add analytics during build
google-analytics-id: 

# add liquid profiler to id bottlenecks
# profile: true

exclude: [docs/, Rakefile, README.md, LICENSE]

# compress CSS output
sass:
  style: compressed
